cmake_minimum_required(VERSION 3.16)
include_guard(GLOBAL)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TARGET_SYSROOT $ENV{HOME}/rpi/sysroot)
set(TOOLS $ENV{HOME}/rpi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf)
set(SYSLIBPATH ${TARGET_SYSROOT}/usr/lib/arm-linux-gnueabihf)
set(CMAKE_PREFIX_PATH $ENV{HOME}/rpi/qt5.15)

#set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
#set(CMAKE_FIND_ROOT_PATH ${TARGET_SYSROOT})
#set(CMAKE_SYSROOT_LINK ${TARGET_SYSROOT})
#set(CMAKE_SYSROOT ${TARGET_SYSROOT})

set(CMAKE_C_COMPILER ${TOOLS}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLS}/bin/arm-linux-gnueabihf-g++)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --sysroot=${TARGET_SYSROOT}")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -pthread")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --sysroot=${TARGET_SYSROOT} -Wl,-rpath-link,${SYSLIBPATH} -Wl,-rpath,'$ORIGIN'")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(XCB_PATH_VARIABLE ${TARGET_SYSROOT}/usr/lib/arm-linux-gnueabihf)

set(GL_INC_DIR ${TARGET_SYSROOT}/usr/include)
set(GL_LIB_DIR ${TARGET_SYSROOT}:${XCB_PATH_VARIABLE}:${TARGET_SYSROOT}/usr:${TARGET_SYSROOT}/usr/lib)

set(EGL_INCLUDE_DIR ${GL_INC_DIR})
set(EGL_LIBRARY ${XCB_PATH_VARIABLE}/libEGL.so)

set(OPENGL_INCLUDE_DIR ${GL_INC_DIR})
set(OPENGL_opengl_LIBRARY ${XCB_PATH_VARIABLE}/libOpenGL.so)

set(OPENGL_glx_LIBRARY ${XCB_PATH_VARIABLE}/libGLX.so)

set(GLIB_INCLUDE_DIR ${GL_INC_DIR})
set(GLIB_LIBRARY ${XCB_PATH_VARIABLE}/libGLESv2.so)

set(GLESv2_INCLUDE_DIR ${GL_INC_DIR})
set(GLESv2_LIBRARY ${XCB_PATH_VARIABLE}/libGLESv2.so)

set(gbm_INCLUDE_DIR ${GL_INC_DIR})
set(gbm_LIBRARY ${XCB_PATH_VARIABLE}/libgbm.so)

set(Libdrm_INCLUDE_DIR ${GL_INC_DIR})
set(Libdrm_LIBRARY ${XCB_PATH_VARIABLE}/libdrm.so)

set(XCB_XCB_INCLUDE_DIR ${GL_INC_DIR})
set(XCB_XCB_LIBRARY ${XCB_PATH_VARIABLE}/libxcb.so)